/* Generated By:JavaCC: Do not edit this line. ExMachinaConstants.java */
package compilador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExMachinaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIS = 5;
  /** RegularExpression Id. */
  int MENOS = 6;
  /** RegularExpression Id. */
  int MULTIPLICA = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int MAIN = 9;
  /** RegularExpression Id. */
  int ABREBLOCO = 10;
  /** RegularExpression Id. */
  int FECHABLOCO = 11;
  /** RegularExpression Id. */
  int ABREPARENT = 12;
  /** RegularExpression Id. */
  int FECHAPARENT = 13;
  /** RegularExpression Id. */
  int FIM = 14;
  /** RegularExpression Id. */
  int TIPOINT = 15;
  /** RegularExpression Id. */
  int TIPOFLOAT = 16;
  /** RegularExpression Id. */
  int TIPOSTRING = 17;
  /** RegularExpression Id. */
  int ATRIBUICAO = 18;
  /** RegularExpression Id. */
  int SEPARADOR = 19;
  /** RegularExpression Id. */
  int IF = 20;
  /** RegularExpression Id. */
  int ELSE = 21;
  /** RegularExpression Id. */
  int IGUAL = 22;
  /** RegularExpression Id. */
  int MAIOR = 23;
  /** RegularExpression Id. */
  int MENOR = 24;
  /** RegularExpression Id. */
  int MAIORIGUAL = 25;
  /** RegularExpression Id. */
  int MENORIGUAL = 26;
  /** RegularExpression Id. */
  int DIFERENTE = 27;
  /** RegularExpression Id. */
  int LOOPFOR = 28;
  /** RegularExpression Id. */
  int LOOPWHILE = 29;
  /** RegularExpression Id. */
  int ABREVETOR = 30;
  /** RegularExpression Id. */
  int FECHAVETOR = 31;
  /** RegularExpression Id. */
  int BREAK = 32;
  /** RegularExpression Id. */
  int CONTINUE = 33;
  /** RegularExpression Id. */
  int RETURN = 34;
  /** RegularExpression Id. */
  int CONSTANTE = 35;
  /** RegularExpression Id. */
  int DIGITO = 36;
  /** RegularExpression Id. */
  int REAL = 37;
  /** RegularExpression Id. */
  int ID = 38;
  /** RegularExpression Id. */
  int CARACTERE = 39;
  /** RegularExpression Id. */
  int CADEIA = 40;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"MagnumOpus\"",
    "\"Aperta\"",
    "\"Clauderes\"",
    "\"Aperi\"",
    "\"Claude\"",
    "\"~\"",
    "\"totum\"",
    "\"fracta\"",
    "\"verbum\"",
    "\"memento\"",
    "\",\"",
    "\"ceteris\"",
    "\"paribus\"",
    "\"idem\"",
    "\"maximus\"",
    "\"minus\"",
    "\"aequalis\"",
    "\"iunior\"",
    "\"diversus\"",
    "\"iterabilis\"",
    "\"dum\"",
    "\"Catena\"",
    "\"Connexa\"",
    "\"mori\"",
    "\"proximus\"",
    "\"reditus\"",
    "<CONSTANTE>",
    "<DIGITO>",
    "<REAL>",
    "<ID>",
    "<CARACTERE>",
    "<CADEIA>",
    "\".\"",
  };

}
