/* Generated By:JavaCC: Do not edit this line. ExMachinaConstants.java */
package compilador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExMachinaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIS = 5;
  /** RegularExpression Id. */
  int MENOS = 6;
  /** RegularExpression Id. */
  int MULTIPLICA = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int MAIN = 9;
  /** RegularExpression Id. */
  int ABREBLOCO = 10;
  /** RegularExpression Id. */
  int FECHABLOCO = 11;
  /** RegularExpression Id. */
  int FIM = 12;
  /** RegularExpression Id. */
  int TIPOINT = 13;
  /** RegularExpression Id. */
  int TIPOFLOAT = 14;
  /** RegularExpression Id. */
  int TIPOSTRING = 15;
  /** RegularExpression Id. */
  int ATRIBUICAO = 16;
  /** RegularExpression Id. */
  int CONSTANTE = 17;
  /** RegularExpression Id. */
  int DIGITO = 18;
  /** RegularExpression Id. */
  int ID = 19;
  /** RegularExpression Id. */
  int CARACTERE = 20;
  /** RegularExpression Id. */
  int CADEIA = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"MagnumOpus\"",
    "\"Aperta\"",
    "\"Clauderes\"",
    "\"~\"",
    "\"totum\"",
    "\"fracta\"",
    "\"verbum\"",
    "\"=\"",
    "<CONSTANTE>",
    "<DIGITO>",
    "<ID>",
    "<CARACTERE>",
    "<CADEIA>",
    "\"(\"",
    "\")\"",
  };

}
